config/routes.rb
Rails.application.routes.draw do
  get 'potin/show'
  get "/team", to: "team#index_team"
  get "/contact", to: "contact#index_contact"
  root "landing_page#index_landing"
  post "/", to:"welcome#index_welcome"
  get "/welcome/:first_name", to:"welcome#index_welcome"
  get "/potin/:id", to:"potin#show_potin", as: "potin_id"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  has_many :users
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :gossip
  has_many :likes, as: :content
  has_many :comment_of_comments
end

app/models/comment_of_comment.rb
class CommentOfComment < ApplicationRecord
  belongs_to :comment
  belongs_to :user
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  has_many :join_gossip_tags
  has_many :tags, through: :join_gossip_tags
  belongs_to :user
  has_many :likes, as: :content
  has_many :comments
end

app/models/join_gossip_tag.rb
class JoinGossipTag < ApplicationRecord
  belongs_to :tag
  belongs_to :gossip
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :content, :polymorphic => true
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  belongs_to :sender, class_name: "User"
  has_many :join_private_message_receivers
  has_many :recipients, through: :join_private_message_receivers
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :join_gossip_tags
  has_many :gossips, through: :join_gossip_tags
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :city
  has_many :gossips
  has_many :comments
  has_many :likes
  has_many :comment_of_comments
  has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
  has_many :received_messages, foreign_key: 'recipient_id', class_name: "JoinPrivateMessageReceiver"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index_contact
  end
end

app/controllers/landing_page_controller.rb
class LandingPageController < ApplicationController
  def index_landing
    puts "$"*60
    puts params["first_name"]
    puts "$"*60
  end
end

app/controllers/potin_controller.rb
class PotinController < ApplicationController
  def show_potin
    @gossip = Gossip.find(params[:id])
  end
end

app/controllers/team_controller.rb
class TeamController < ApplicationController
  def index_team
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index_welcome
    @gossips = Gossip.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/landing_page_helper.rb
module LandingPageHelper
end

app/helpers/potin_helper.rb
module PotinHelper
end

app/helpers/team_helper.rb
module TeamHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/contact/index_contact.html.erb
<html>  

<head>
  <title>The Gossip Project - Contact </title>
</head>  

<body>
  <h1>Vous souhaitez nous contacter ?</h1>
    
  <p>
  Jade Caillot : 118 218<br>
  Grégoire Aubert : vtf@gmail.com
  </p>  

</body>

</html>

app/views/landing_page/index_landing.html.erb
<html>  

<head>
  <title>The Gossip Project</title>
</head>  

<body>
  <h1>Pas si vite, moussaillon ! Donne nous ton petit nom</h1><br><br>

  <form action="/", method="post">
    Entre ton prénom :
    <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token %>">
    <input type="text" name="first_name">
    <input type="submit" value="entre donc">
  </form>
    
</body>

</html>

app/views/potin/show_potin.html.erb
<html>  

  <head>
    <title>The Gossip Project</title>
  </head>  
  
  <body>
    <h1>Potin n°<%=params["id"]%></h1><br><br>   
    Titre du potin : <%= @gossip.title%><br>
    Contenu du potin : <%= @gossip.content %><br>
    Auteur du potin : <%= @gossip.user.first_name %><br>
    Date de création du potin : <%= @gossip.created_at%><br>  
    
  </body>
    
</html>

app/views/team/index_team.html.erb
<html>  

<head>
  <title>The Gossip Project - l'équipe </title>
</head>  

<body>
  <h1>Voici la présentation de l'équipe</h1>
    
  <p>
  Jade Caillot<br>
  Grégoire Aubert
  </p>  

</body>

</html>

app/views/welcome/index_welcome.html.erb
<html>  

<head>
  <title>The Gossip Project</title>
</head>  

<body>
  <h1>Bienvenue <%=params["first_name"]%> sur la page des potins !</h1><br><br>

  <p>Voici la liste de tous les potins</p><br>
  <% @gossips.all.each do |gossip|%><br><br>
    Numéro du potin : <%= gossip.id %><br>
    Titre : <%= gossip.title %><br>
    Auteur : <%= gossip.user.first_name %><br>
    Lien : <%= link_to "Cliquez ici", potin_id_path(@id=gossip.id) %>
  <% end %>
</body>

</html>