config/routes.rb
Rails.application.routes.draw do
  get 'potin/show'
  get "/team", to: "team#index_team"
  get "/contact", to: "contact#index_contact"
  root "landing_page#index_landing"
  post "/", to:"welcome#index_welcome"
  get "/welcome/:first_name", to:"welcome#index_welcome"
  get "/potin/:id", to:"potin#show_potin", as: "potin_id"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  has_many :users
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :gossip
  has_many :likes, as: :content
  has_many :comment_of_comments
end

app/models/comment_of_comment.rb
class CommentOfComment < ApplicationRecord
  belongs_to :comment
  belongs_to :user
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  has_many :join_gossip_tags
  has_many :tags, through: :join_gossip_tags
  belongs_to :user
  has_many :likes, as: :content
  has_many :comments
end

app/models/join_gossip_tag.rb
class JoinGossipTag < ApplicationRecord
  belongs_to :tag
  belongs_to :gossip
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :content, :polymorphic => true
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  belongs_to :sender, class_name: "User"
  has_many :join_private_message_receivers
  has_many :recipients, through: :join_private_message_receivers
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :join_gossip_tags
  has_many :gossips, through: :join_gossip_tags
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :city
  has_many :gossips
  has_many :comments
  has_many :likes
  has_many :comment_of_comments
  has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
  has_many :received_messages, foreign_key: 'recipient_id', class_name: "JoinPrivateMessageReceiver"
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index_contact
  end
end

app/controllers/potin_controller.rb
class PotinController < ApplicationController
  def show_potin
    @gossip = Gossip.find(params[:id])
  end
end

app/controllers/team_controller.rb
class TeamController < ApplicationController
  def index_team
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index_welcome
    @gossips = Gossip.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/landing_page_helper.rb
module LandingPageHelper
end

app/helpers/potin_helper.rb
module PotinHelper
end

app/helpers/team_helper.rb
module TeamHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheGossipProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>    
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/da8b50c52a.js" crossorigin="anonymous">
    </script>
    
<nav class="navbar navbar-expand-lg navbar-light bg-light">
<a class="navbar-brand" href="#">The Gossip Project</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <%= link_to "Accueil", root_path, :class => "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Team", team_path, :class => "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Contact", contact_path, :class => "nav-link" %>
      </li>
    </ul>
  </div>
</nav>
  </head>  
  <body>
    <%= yield %>
  </body>
</html>